version: '3'

services:
    app:
        container_name: app
        build:
            context: ..
            dockerfile: ./docker/Dockerfile
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - 3000:80
