stages:
    - build
    - deploy
build:
    stage: build
    script:
        - echo “Building docker image”
        - docker-compose -f ./docker/docker-compose.yml down
        - docker-compose -f ./docker/docker-compose.yml build
        - echo “Build successful”
    only:
        - master
deploy:
    stage: deploy
    script:
        - echo “Starting docker compose”
        - docker-compose -f ./docker/docker-compose.yml up
        - echo “Done”
    environment:
        name: production
    only:
        - master
